
- name : create ssh key file
  shell: ssh-keygen -t rsa -f ~/.ssh/id_rsa -q -N ""
  args:
    creates: ~/.ssh/id_rsa

- name: fetch the public key to ansible manager server from rancher-server
  fetch:
    src: ~/.ssh/id_rsa.pub
    dest: data/
    flat: yes
