
- name : copy ssh public key to remote server
  authorized_key: user=rts key="{{ lookup('file', 'data/id_rsa.pub') }}"

# - name: debug hostname
#   debug: msg="hostname is {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
#   # debug: msg="host ip is {{ hostvars[item]['ansible_default_ipv4']['address'] }}"
#   with_items:  groups['all']

- name: register all host ip of inventory file
  debug: msg="{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address']  }}"
  register: host_ip
  with_items: groups['all']


- name: For each host, scan for its ssh public key
  shell: "ssh-keyscan {{ item.msg }} "
  with_items: "{{ host_ip.results }}"
  register: ssh_known_host_results
  ignore_errors: yes

- name: print ip for debugging
  debug:
    msg: "IP is  {{ item.item.msg }}"
  with_items: "{{ ssh_known_host_results.results }}"
#
- name: Add/update the public key in the '{{ ssh_known_hosts_file }}'
  known_hosts:
    name: "{{ item.item.msg }}"
    key: "{{ item.stdout }}"
    path: "/home/rts/.ssh/known_hosts"
  with_items: "{{ ssh_known_host_results.results }}"
