version: '2'
services:
  vertx-web:
    scale: 1
    start_on_create: true
  lb-api:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: vertx-web
        source_port: 7070
        target_port: 7070
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  mariadb-test:
    scale: 1
    start_on_create: true
